import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const register = readFileSync(new URL('../src/views/Register.vue', import.meta.url), 'utf8')
const users = readFileSync(new URL('../src/views/HouseholdUsers.vue', import.meta.url), 'utf8')
const login = readFileSync(new URL('../src/views/Login.vue', import.meta.url), 'utf8')
const accountMembers = readFileSync(new URL('../src/views/AccountMembers.vue', import.meta.url), 'utf8')

test('登录页使用家庭资产品牌视觉且注册支持白名单或家庭邀请', () => {
  assert.match(login, /让每一笔家庭资产/)
  assert.match(login, /资产趋势/)
  assert.match(login, /家庭协作/)
  assert.match(login, /白名单注册/)
  assert.match(register, /白名单用户可创建独立家庭/)
  assert.match(register, /加入已有家庭只需要有效邀请码/)
  assert.match(register, /家庭邀请码/)
  assert.match(register, /authApi\.inviteInfo/)
  assert.match(register, /authApi\.register/)
  assert.match(login, /clearPageCaches\(\)/)
  assert.match(register, /clearPageCaches\(\)/)
  assert.match(login, /window\.location\.replace\('\/'\)/)
  assert.match(register, /window\.location\.replace\('\/'\)/)
})

test('我的页面整合家庭用户管理', () => {
  assert.match(accountMembers, /HouseholdUsers/)
  assert.match(accountMembers, /activeTab === 'users'/)
  assert.match(users, /添加白名单/)
  assert.match(users, /注册白名单/)
  assert.match(users, /白名单用户注册后会创建自己的独立家庭/)
  assert.match(users, /独立家庭所有者/)
  assert.match(users, /householdApi\.addWhitelist/)
  assert.match(users, /邀请家人/)
  assert.match(users, /最多邀请10位家人/)
  assert.match(users, /受邀用户无需注册白名单/)
  assert.match(users, /householdApi\.createInvite/)
  assert.match(users, /onActivated\(\(\) =>/)
  assert.match(users, /家庭用户刷新失败/)
  assert.match(users, /isSuperAdmin/)
  assert.match(users, /super_admin: '超级管理员'/)
  assert.match(users, /只读成员/)
  assert.match(users, /管理员/)
  assert.match(users, /停用用户/)
})
